sudo: required
services:
  - docker

before_install:
  - docker build -t ekarychkovsky/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ekarychkovsky/udemy-docker-react npm run test