sudo: required
services:
  - docker

before_install:
  - docker build -t ekarychkovsky/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ekarychkovsky/udemy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: udemy-docker-react
  env: UdemyDockerReact-env
  bucket_name: elasticbeanstalk-eu-west-1-805957902858
  bucket_path: udemy-docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY